"""Lock down the routing contract between routing keys and specs.

Two contracts under test:

1. **Auto-generated routing keys**: every per-kind ``ArtifactSpec``
   subclass exposes UPPER_CASE :class:`FieldRef` constants for its
   ArtifactField-typed fields, generated by
   :meth:`ArtifactField.__pydantic_init_subclass__`. Capture sites
   reference them off the spec directly.

2. **Strict ``attach_class_captures`` enforcement**: paths that
   reference a non-existent attribute, a non-ArtifactField target,
   or use bracket access incompatibly with the slot's container
   shape raise :class:`RuntimeError` immediately. The walker is
   permissive only on **runtime gaps** — slot value ``None``, key
   missing in a runtime list/dict — which are real "spec wasn't
   populated" cases, not bugs.
"""
from __future__ import annotations

import pytest

from llm_pipeline.graph.spec import ValidationIssue, ValidationLocation
from llm_pipeline.artifacts import (
    ExtractionSpec,
    KIND_EXTRACTION,
    KIND_REVIEW,
    KIND_STEP,
    PromptData,
    PromptVariableDefs,
    ReviewSpec,
    StepSpec,
)
from llm_pipeline.artifacts.base.fields import FieldRef


# ---------------------------------------------------------------------------
# Contract 1: auto-generated routing keys
# ---------------------------------------------------------------------------


class TestAutoGeneratedFieldRefs:
    """Every ArtifactField-typed slot on a spec exposes an UPPER_CASE
    :class:`FieldRef` constant. Auto-generated by
    :meth:`ArtifactField.__pydantic_init_subclass__`."""

    def test_step_spec_routing_keys(self):
        assert StepSpec.INPUTS == FieldRef("inputs")
        assert StepSpec.INSTRUCTIONS == FieldRef("instructions")
        assert StepSpec.PREPARE == FieldRef("prepare")
        assert StepSpec.RUN == FieldRef("run")
        assert StepSpec.PROMPT == FieldRef("prompt")
        assert StepSpec.TOOLS == FieldRef("tools")

    def test_extraction_spec_routing_keys(self):
        assert ExtractionSpec.INPUTS == FieldRef("inputs")
        assert ExtractionSpec.TABLE == FieldRef("table")

    def test_review_spec_routing_keys(self):
        assert ReviewSpec.INPUTS == FieldRef("inputs")
        assert ReviewSpec.OUTPUT == FieldRef("output")

    def test_prompt_data_routing_keys(self):
        # Sub-component (ArtifactField, not ArtifactSpec) — auto-gen
        # works the same way.
        assert PromptData.VARIABLES == FieldRef("variables")

    def test_primitives_skipped(self):
        # ``StepSpec.cls`` is a str, ``StepSpec.kind`` is a Literal —
        # not ArtifactField-typed, so no UPPER_CASE constant generated.
        assert not hasattr(StepSpec, "CLS") or not isinstance(
            StepSpec.CLS, FieldRef,
        )
        # ``ReviewSpec.webhook_url`` is str | None — primitive.
        assert not hasattr(ReviewSpec, "WEBHOOK_URL") or not isinstance(
            ReviewSpec.WEBHOOK_URL, FieldRef,
        )


# ---------------------------------------------------------------------------
# Contract 2: strict raises on bogus paths at routing time
# ---------------------------------------------------------------------------


def _bogus_capture_class(*, path: str | None = None, field: str | None = None) -> type:
    """Build a throwaway class whose ``_init_subclass_errors`` carries
    a single issue with the requested ``location.path`` / ``location.field``."""

    class _Holder:
        _init_subclass_errors = [
            ValidationIssue(
                severity="error", code="probe",
                message="probe",
                location=ValidationLocation(path=path, field=field),
            )
        ]

    return _Holder


class TestStrictAttachContract:
    """``attach_class_captures`` raises on broken routing paths
    rather than silently falling back to ``self.issues`` (which
    would lose the issue from any structurally-routed UI surface).
    """

    def _empty_step_spec(self) -> StepSpec:
        return StepSpec(
            name="probe", cls="m.Probe", source_path="/probe.py",
        )

    def test_unknown_attr_raises(self):
        spec = self._empty_step_spec()
        bad_cls = _bogus_capture_class(path="inptus")  # typo
        with pytest.raises(RuntimeError) as exc_info:
            spec.attach_class_captures(bad_cls)
        msg = str(exc_info.value)
        assert "probe" in msg          # issue code surfaces
        assert "inptus" in msg          # bad path surfaces
        assert "no field" in msg        # actionable hint

    def test_primitive_attr_raises(self):
        # ``StepSpec.cls`` (inherited) is str — primitive, not
        # ArtifactField-typed. Routing to it should raise.
        spec = self._empty_step_spec()
        bad_cls = _bogus_capture_class(path="cls")
        with pytest.raises(RuntimeError, match="not ArtifactField-typed"):
            spec.attach_class_captures(bad_cls)

    def test_list_without_bracket_raises(self):
        # ``StepSpec.tools`` is list[ArtifactRef] — bracket required.
        spec = self._empty_step_spec()
        bad_cls = _bogus_capture_class(path="tools")
        with pytest.raises(RuntimeError, match="must use bracketed"):
            spec.attach_class_captures(bad_cls)

    def test_bracket_on_plain_field_raises(self):
        spec = self._empty_step_spec()
        bad_cls = _bogus_capture_class(path="inputs[x]")
        with pytest.raises(RuntimeError, match="single ArtifactField"):
            spec.attach_class_captures(bad_cls)

    def test_path_none_routes_to_top_level(self):
        spec = self._empty_step_spec()
        bad_cls = _bogus_capture_class(path=None)
        spec.attach_class_captures(bad_cls)
        assert [i.code for i in spec.issues] == ["probe"]

    def test_legacy_field_kwarg_still_works(self):
        # Capture sites that haven't migrated to ``path=`` still set
        # ``field=`` for top-level routing. The walker treats it as
        # a single-segment path.
        spec = self._empty_step_spec()
        bad_cls = _bogus_capture_class(field="inputs")
        # ``inputs`` is None at runtime → permissive: lands on parent.
        spec.attach_class_captures(bad_cls)
        assert [i.code for i in spec.issues] == ["probe"]


class TestPermissiveOnRuntimeGaps:
    """The walker is permissive only on real "spec wasn't populated"
    runtime cases — the structural shape is correct, the runtime
    container just doesn't have the addressed element."""

    def test_artifact_field_typed_runtime_none_routes_top_level(self):
        spec = StepSpec(
            name="probe", cls="m.Probe", source_path="/probe.py",
        )
        assert spec.inputs is None
        bad_cls = _bogus_capture_class(path="inputs")
        spec.attach_class_captures(bad_cls)
        assert [i.code for i in spec.issues] == ["probe"]

    def test_missing_list_key_routes_to_parent(self):
        spec = StepSpec(
            name="probe", cls="m.Probe", source_path="/probe.py",
        )
        bad_cls = _bogus_capture_class(path="tools[unknown]")
        spec.attach_class_captures(bad_cls)
        assert [i.code for i in spec.issues] == ["probe"]


# ---------------------------------------------------------------------------
# Spot-check across kinds
# ---------------------------------------------------------------------------


class TestStrictAttachAcrossKinds:
    """Confirm the strict contract is inherited cleanly by every
    per-kind ArtifactSpec subclass — not just StepSpec."""

    def test_extraction_spec_raises_on_unknown_attr(self):
        spec = ExtractionSpec(
            name="probe", cls="m.Probe", source_path="/probe.py",
        )
        bad_cls = _bogus_capture_class(path="nope")
        with pytest.raises(RuntimeError, match="no field"):
            spec.attach_class_captures(bad_cls)

    def test_review_spec_raises_on_primitive_target(self):
        spec = ReviewSpec(
            name="probe", cls="m.Probe", source_path="/probe.py",
        )
        # ReviewSpec.webhook_url is str | None — primitive.
        bad_cls = _bogus_capture_class(path="webhook_url")
        with pytest.raises(RuntimeError, match="not ArtifactField-typed"):
            spec.attach_class_captures(bad_cls)

    def test_prompt_data_routes_variables_path(self):
        prompt = PromptData(
            variables=PromptVariableDefs(json_schema={"type": "object"}),
            yaml_path="/tmp/x.yaml",
        )
        bad_cls = _bogus_capture_class(path=str(PromptData.VARIABLES))
        prompt.attach_class_captures(bad_cls)
        assert [i.code for i in prompt.variables.issues] == ["probe"]
        assert prompt.issues == []

    def test_subfield_passes_through_unchanged(self):
        # ``subfield`` is UI-only metadata — the router ignores it.
        prompt = PromptData(
            variables=PromptVariableDefs(json_schema={"type": "object"}),
            yaml_path="/tmp/x.yaml",
        )

        class _Holder:
            _init_subclass_errors = [
                ValidationIssue(
                    severity="error", code="missing_field_description",
                    message="probe",
                    location=ValidationLocation(
                        path=str(PromptData.VARIABLES),
                        subfield="sentiment",
                    ),
                )
            ]

        prompt.attach_class_captures(_Holder)
        landed = prompt.variables.issues
        assert len(landed) == 1
        assert landed[0].location.subfield == "sentiment"
