/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as LiveRouteImport } from './routes/live'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvalsIndexRouteImport } from './routes/evals.index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ReviewTokenRouteImport } from './routes/review/$token'
import { Route as EvalsDatasetIdRouteImport } from './routes/evals.$datasetId'
import { Route as EvalsDatasetIdRunsRunIdRouteImport } from './routes/evals.$datasetId.runs.$runId'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsIndexRoute = EvalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvalsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsDatasetIdRoute = EvalsDatasetIdRouteImport.update({
  id: '/$datasetId',
  path: '/$datasetId',
  getParentRoute: () => EvalsRoute,
} as any)
const EvalsDatasetIdRunsRunIdRoute = EvalsDatasetIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => EvalsDatasetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/editor': typeof EditorRoute
  '/evals': typeof EvalsRouteWithChildren
  '/live': typeof LiveRoute
  '/pipelines': typeof PipelinesRoute
  '/prompts': typeof PromptsRoute
  '/reviews': typeof ReviewsRoute
  '/evals/$datasetId': typeof EvalsDatasetIdRouteWithChildren
  '/review/$token': typeof ReviewTokenRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/': typeof EvalsIndexRoute
  '/evals/$datasetId/runs/$runId': typeof EvalsDatasetIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/editor': typeof EditorRoute
  '/live': typeof LiveRoute
  '/pipelines': typeof PipelinesRoute
  '/prompts': typeof PromptsRoute
  '/reviews': typeof ReviewsRoute
  '/evals/$datasetId': typeof EvalsDatasetIdRouteWithChildren
  '/review/$token': typeof ReviewTokenRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals': typeof EvalsIndexRoute
  '/evals/$datasetId/runs/$runId': typeof EvalsDatasetIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/editor': typeof EditorRoute
  '/evals': typeof EvalsRouteWithChildren
  '/live': typeof LiveRoute
  '/pipelines': typeof PipelinesRoute
  '/prompts': typeof PromptsRoute
  '/reviews': typeof ReviewsRoute
  '/evals/$datasetId': typeof EvalsDatasetIdRouteWithChildren
  '/review/$token': typeof ReviewTokenRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/': typeof EvalsIndexRoute
  '/evals/$datasetId/runs/$runId': typeof EvalsDatasetIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creator'
    | '/editor'
    | '/evals'
    | '/live'
    | '/pipelines'
    | '/prompts'
    | '/reviews'
    | '/evals/$datasetId'
    | '/review/$token'
    | '/runs/$runId'
    | '/evals/'
    | '/evals/$datasetId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creator'
    | '/editor'
    | '/live'
    | '/pipelines'
    | '/prompts'
    | '/reviews'
    | '/evals/$datasetId'
    | '/review/$token'
    | '/runs/$runId'
    | '/evals'
    | '/evals/$datasetId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/creator'
    | '/editor'
    | '/evals'
    | '/live'
    | '/pipelines'
    | '/prompts'
    | '/reviews'
    | '/evals/$datasetId'
    | '/review/$token'
    | '/runs/$runId'
    | '/evals/'
    | '/evals/$datasetId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRoute
  EditorRoute: typeof EditorRoute
  EvalsRoute: typeof EvalsRouteWithChildren
  LiveRoute: typeof LiveRoute
  PipelinesRoute: typeof PipelinesRoute
  PromptsRoute: typeof PromptsRoute
  ReviewsRoute: typeof ReviewsRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/': {
      id: '/evals/'
      path: '/'
      fullPath: '/evals/'
      preLoaderRoute: typeof EvalsIndexRouteImport
      parentRoute: typeof EvalsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/$datasetId': {
      id: '/evals/$datasetId'
      path: '/$datasetId'
      fullPath: '/evals/$datasetId'
      preLoaderRoute: typeof EvalsDatasetIdRouteImport
      parentRoute: typeof EvalsRoute
    }
    '/evals/$datasetId/runs/$runId': {
      id: '/evals/$datasetId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/evals/$datasetId/runs/$runId'
      preLoaderRoute: typeof EvalsDatasetIdRunsRunIdRouteImport
      parentRoute: typeof EvalsDatasetIdRoute
    }
  }
}

interface EvalsDatasetIdRouteChildren {
  EvalsDatasetIdRunsRunIdRoute: typeof EvalsDatasetIdRunsRunIdRoute
}

const EvalsDatasetIdRouteChildren: EvalsDatasetIdRouteChildren = {
  EvalsDatasetIdRunsRunIdRoute: EvalsDatasetIdRunsRunIdRoute,
}

const EvalsDatasetIdRouteWithChildren = EvalsDatasetIdRoute._addFileChildren(
  EvalsDatasetIdRouteChildren,
)

interface EvalsRouteChildren {
  EvalsDatasetIdRoute: typeof EvalsDatasetIdRouteWithChildren
  EvalsIndexRoute: typeof EvalsIndexRoute
}

const EvalsRouteChildren: EvalsRouteChildren = {
  EvalsDatasetIdRoute: EvalsDatasetIdRouteWithChildren,
  EvalsIndexRoute: EvalsIndexRoute,
}

const EvalsRouteWithChildren = EvalsRoute._addFileChildren(EvalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRoute,
  EditorRoute: EditorRoute,
  EvalsRoute: EvalsRouteWithChildren,
  LiveRoute: LiveRoute,
  PipelinesRoute: PipelinesRoute,
  PromptsRoute: PromptsRoute,
  ReviewsRoute: ReviewsRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
