/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as LiveRouteImport } from './routes/live'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'

const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/editor': typeof EditorRoute
  '/live': typeof LiveRoute
  '/pipelines': typeof PipelinesRoute
  '/prompts': typeof PromptsRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/editor': typeof EditorRoute
  '/live': typeof LiveRoute
  '/pipelines': typeof PipelinesRoute
  '/prompts': typeof PromptsRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/editor': typeof EditorRoute
  '/live': typeof LiveRoute
  '/pipelines': typeof PipelinesRoute
  '/prompts': typeof PromptsRoute
  '/runs/$runId': typeof RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creator'
    | '/editor'
    | '/live'
    | '/pipelines'
    | '/prompts'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creator'
    | '/editor'
    | '/live'
    | '/pipelines'
    | '/prompts'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/creator'
    | '/editor'
    | '/live'
    | '/pipelines'
    | '/prompts'
    | '/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRoute
  EditorRoute: typeof EditorRoute
  LiveRoute: typeof LiveRoute
  PipelinesRoute: typeof PipelinesRoute
  PromptsRoute: typeof PromptsRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRoute,
  EditorRoute: EditorRoute,
  LiveRoute: LiveRoute,
  PipelinesRoute: PipelinesRoute,
  PromptsRoute: PromptsRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
