"""AUTOGENERATED. DO NOT EDIT.

Regenerated on each `uv run llm-pipeline generate` from the matching `llm-pipeline-prompts/{name}.yaml`. Hand edits will be overwritten on the next generate run."""
from __future__ import annotations

from pydantic import Field

from llm_pipeline.prompts import PromptVariables


class SummaryPrompt(PromptVariables):
    """Variables for the 'summary' Phoenix prompt."""

    text: str = Field(description='Input text to summarize')
    sentiment: str = Field(description='Previously detected sentiment')
    primary_topic: str = Field(description='Primary topic extracted from text')
