"""AUTOGENERATED. DO NOT EDIT.

Regenerated on each `uv run llm-pipeline generate` from the matching `llm-pipeline-prompts/{name}.yaml`. Hand edits will be overwritten on the next generate run."""
from __future__ import annotations

from pydantic import Field

from llm_pipeline.prompts import PromptVariables


class TopicExtractionPrompt(PromptVariables):
    """Variables for the 'topic_extraction' Phoenix prompt."""

    text: str = Field(description='Input text to extract topics from')
    sentiment: str = Field(description='Previously detected sentiment')
